### ISSUE TITLE
Unit tests for scalar Ion Types 

### ISSUE THREAD

**Issue by therapon** [amzn/ion-hash-go#15]
Unit tests for simple scalar (non-container) types. 

* null -- all of them 
* int 
* float 
* Decimal 
    * Include tests that exercise precision cases for Decimal
* string 
* symbol (without symbol tables for now) 
* clob 
* blob

The other Ion Hash implementation should be a good seed for generating some tests here.

**Comment by justing-bq** [comment]
Resolved by https://github.com/amzn/ion-hash-go/pull/39
